<?php

$AWS_ACCESS_KEY_ID = "SECRET KEY HERE"; //DO NOT COMMIT ACTUAL KEYS TO GITHUB
$AWS_SECRET_ACCESS_KEY = "SECRET KEY HERE";
$SERVICE_NAME = "AWSMechanicalTurkRequester";
$SERVICE_VERSION = "2014-08-15";



?>
